name: AstShop
version: '${project.version}'
main: fr.myxbow.astshop.AstShop
api-version: 1.19
depend: [ Vault ]
authors: [ MyxBow ]
description: Shop Admin
website: https://myx.astbow.com/
commands:
  shop:
    aliases:
      - magasin
      - shops
      - magasins
      - boutique
      - boutiques
